### ISSUE TITLE
entrypoint?

### ISSUE THREAD

**Issue by corbosman** [hsmade/certbot-dns-transip#18]
Hi, did you mean to use CMD instead of ENTRYPOINT? It would be nice if we could just have a certbot entrypoint.

**Comment by hsmade** [comment]
Hey, I used to build all my dockers with CMD, to have easier control (ready: lazy). But having it as entrypoint makes more sense indeed. I'll change it

**Comment by hsmade** [comment]
I feel stupid, even the readme assumes entrypoint :D
