### ISSUE TITLE
WSDL broken

### ISSUE THREAD

**Issue by zonaut** [hsmade/certbot-dns-transip#19]
Hi,

this seems broken. I get an error on the XML schema.
The transip dependency has fixed this in version 2.1.1 
Link to the issue https://github.com/benkonrath/transip-api/commit/51c6cb98e6f4536c2b4a120c8569ad4dc3b41825

**Comment by hsmade** [comment]
fixed by https://github.com/hsmade/certbot-dns-transip/pull/20
