### ISSUE TITLE
Can't build requirement suds-jurko anymore with setuptools

### ISSUE THREAD

**Issue by siccovansas** [hsmade/certbot-dns-transip#29]
I tried to update my Certbot Docker container (which contains certbot-dns-transip) from 1.19.0 to 1.20.0, but it fails:

```
Collecting suds-jurko~=0.6
  Downloading suds-jurko-0.6.zip (255 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ggo5hlmd/suds-jurko_42e55aecc9604ca5ac9b5db582f92802/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ggo5hlmd/suds-jurko_42e55aecc9604ca5ac9b5db582f92802/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-av1c36dp
         cwd: /tmp/pip-install-ggo5hlmd/suds-jurko_42e55aecc9604ca5ac9b5db582f92802/
    Complete output (1 lines):
    error in suds-jurko setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d0/88/f3bed9b494e0dae26bd55e5f3d527b8244208125024727267e8109956a11/suds-jurko-0.6.zip#sha256=1cb7252cb13018fc32887c3a834ed7c6648a5b5c4c159be5806da2e1785399e8 (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading suds-jurko-0.6.tar.bz2 (143 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ggo5hlmd/suds-jurko_9a3599eb9c584d76b1cda189347cff0d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ggo5hlmd/suds-jurko_9a3599eb9c584d76b1cda189347cff0d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-j1lrfyjl
         cwd: /tmp/pip-install-ggo5hlmd/suds-jurko_9a3599eb9c584d76b1cda189347cff0d/
    Complete output (1 lines):
    error in suds-jurko setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bd/6f/54fbf0999a606680d27c69b1ad12dfff62768ecb9fe48524cebda6eb4423/suds-jurko-0.6.tar.bz2#sha256=29edb72fd21e3044093d86f33c66cf847c5aaab26d64cb90e69e528ef014e57f (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement suds-jurko~=0.6 (from certbot-dns-transip) (from versions: 0.4.1.jurko.1, 0.4.1.jurko.2, 0.4.1.jurko.3, 0.4.1.jurko.4, 0.4.1.jurko.5, 0.5, 0.6)
ERROR: No matching distribution found for suds-jurko~=0.6
ERROR: Service 'c-certbot' failed to build : The command '/bin/sh -c pip install certbot-dns-transip==0.3.0' returned a non-zero code: 1
```

Apparently `suds-jurko` (the latest release, 0.6, is from 2014 btw) uses `use_2to3`, but `setuptools` removed `use_2to3` since version 58 (due to a bug you can [still use version 58.0.0 and 58.0.1](https://github.com/pypa/setuptools/issues/2781#issuecomment-917185367), but the `setuptools` versions after 58.0.1 don't work), and Certbot's Docker container uses `setuptools` 58.0.4 [since 1.20.0](https://github.com/certbot/certbot/commit/fc02b10560b5f04b661040b9683cda343de17e61#diff-1ed4efd531f910f92b0dd60fadf0be32ec199b1e1f75fe71c37cdcc567938091L151-R151).

Currently I use `RUN pip install setuptools==58.0.1` in my Dockerfile to be able to build Certbot with certbot-dns-transip, but that is not really futureproof I guess :). I guess certbot-dns-transip should either use an alternative for `suds-jurko` or `suds-jurko` should be forked and updated so it doesn't need `use_2to3`?

Thanks for creating and maintaining this plugin :)!

**Comment by hsmade** [comment]
Suds is actually used by the transip library itself (which is not part of this repo). I import it to catch an error explicitly.
Let me check how the transip lib is handing this

**Comment by hsmade** [comment]
Right. So disclaimer here: I don't use this repo for a long time already. But I'm happy to maintain it, as it does seem to be used.

Now it seems that transip has deprecated their SOAP api, and asks users to use the REST api instead.
The suds requirement is for the errors that the SOAP version of the transip lib returns.

I'll have a look how hard it is to rewrite my certbot plugin into using the REST api instead, which would then also get rid of the dependency on suds.

**Comment by siccovansas** [comment]
@hsmade Thanks a lot 🎉🎉! I'll try out the new version 👌.

**Comment by siccovansas** [comment]
Tested and it works great! Thanks again :100:!

**Comment by peterdk** [comment]
Great to hear this is fixed, I just got  a email from Transip that I use SOAP api somehow, and this is the only thing that I use. I'll check it out!
