### ISSUE TITLE
Typo in USAGE.rst

### ISSUE THREAD

**Issue by Kleinendorst** [hsmade/certbot-dns-transip#3]
Thanks for making this plugin.
I noticed a minor issue in the USAGE.rst.

```bash
--certbot-dns-transipdns-transip-propagation-seconds
```

should be 

```bash
--certbot-dns-transip:dns-transip-propagation-seconds
```

**Comment by Kleinendorst** [comment]
Apparently something else was the problem, I see there is no typo actually.

**Comment by BartVB** [comment]
Stable docs are still incorrect:

https://certbot-dns-transip.readthedocs.io/en/stable/usage.html

**Comment by hsmade** [comment]
Fixed that
