### ISSUE TITLE
Not compatible with ACME 2.0

### ISSUE THREAD

**Issue by wimmez** [hsmade/certbot-dns-transip#46]
In ACME 2.0 the zope based interfaces in certbot.interfaces have been removed in favor of the abc based interfaces found in the same module.
The current implementation does not seem to work anymore and an update would be appreciated.

Release notes: https://github.com/certbot/certbot/releases/tag/v2.0.0

**Comment by hsmade** [comment]
Thanks for reporting!

This should be fixed in release 0.5.0. 
Could you please test that and let me know?

**Comment by barreljan** [comment]
The docker image is yet to be updated so I have tested it as well with a manual update of the fix. And it seems to work now.

**Comment by hsmade** [comment]
For some reason my github pipeline indeed uploaded latest with version `0.4.3`. I'll have to look at that.
I've now uploaded tag `0.5.0` and updated the `latest` tag as well.
Thanks for letting me know!
