### ISSUE TITLE
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested

### ISSUE THREAD

**Issue by RaymiiOrg** [hsmade/certbot-dns-transip#48]
Using the example docker command fails with the following error:

    WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested

Adding the flag `--platform linux/amd64` does not help. Docker hub shows the latest tag being only for arm64. 

Building the docker image on an x64 host works just fine, using certbot, renewing, etc.

**Comment by hsmade** [comment]
hmm, odd. I'll have a look. Thx for reporting

**Comment by hsmade** [comment]
Fixed with the latest image tag on the docker hub. It's now multi-arch :)
