### ISSUE TITLE
Expire of all records must be the same

### ISSUE THREAD

**Issue by BartVB** [hsmade/certbot-dns-transip#6]
Thank you for creating this plugin!

I'm trying to get this to work (stable version on Debian Jessie) but this results in:

```
Error adding TXT record using the Transip API: Server raised fault: 'the expire of all records in an rrset must be all the same: _acme-challenge 86400 TXT 4PIHj9PV6t6Dn7XgFcuIztXR1kJTdXqsiMMD1i7GofU
the expire of all records in an rrset must be all the same: _acme-challenge 86400 TXT egkkcGfigtTgaxoBSlBsI8hyST5wtSQek9R9ubxnYdk
the expire of all records in an rrset must be all the same: _acme-challenge 1 TXT eWMectsKzA6yLMyNdaWERPxtEz2R4RmYxiDqyQoqbdc'
```

I'm trying to create a wildcard cert with: `-d *.example.com -d example.com`.

**Comment by hsmade** [comment]
Hya!

I tried to reproduce using a docker container with jessie, but could not:

```
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for hsmade.com
dns-01 challenge for hsmade.com
Successfully added TXT record
Successfully added TXT record
Waiting 240 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
Removing TXT record with name: _acme-challenge
Removing TXT record with name: _acme-challenge
```

Could you please try to reproduce using docker? I just uploaded an image for that using the latest version (see github readme)

**Comment by BartVB** [comment]
Lots of other stuff higher on the TODO-list :)

I gave this another try. I was pretty sure that this was caused by my ancient Debian install (Jessie). Recently upgraded to Debian Buster and gave it another try. This resulted in the exact same error.

The plugin has been installed with:

```
cd /opt/eff.org/certbot/venv
source bin/activate
python -m pip install certbot-dns-transip
deactivate
```
(I'm using certbot-auto)

Then:

```
$ certbot-auto certonly -d 'site.nl,*.site.nl' -a certbot-dns-transip:dns-transip --certbot-dns-transip:dns-transip-credentials /etc/letsencrypt/transip.ini --certbot-dns-transip:dns-transip-propagation-seconds 240
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator certbot-dns-transip:dns-transip, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for site.nl
dns-01 challenge for site.nl
<suds.sax.document.Document instance at 0x7e16bdd63050>
Error adding TXT record using the Transip API: Server raised fault: 'the expire of all records in an rrset must be all the same: _acme-challenge 60 TXT O7mdcztSaa4N_KIDo0j4NCubBBs-CETCxNSI6eMkZgo
the expire of all records in an rrset must be all the same: _acme-challenge 60 TXT YnggCckBOruTAn4QVOWI43lIPpBaK2qk6IHqLURxbD0
the expire of all records in an rrset must be all the same: _acme-challenge 1 TXT UfrltIvlnh2S8t0Ty2C02vNevlDxV6jDd3aXWOQtaMW'
Cleaning up challenges
Error adding TXT record using the Transip API: Server raised fault: 'the expire of all records in an rrset must be all the same: _acme-challenge 60 TXT O7mdcztSaa4N_KIDo0j4NCubBBs-CETCxNSI6eMkZgo
the expire of all records in an rrset must be all the same: _acme-challenge 60 TXT YnggCckBOruTAn4QVOWI43lIPpBaK2qk6IHqLURxbD0
the expire of all records in an rrset must be all the same: _acme-challenge 1 TXT UfrltIvlnh2S8t0Ty2C02vNevlDxV6jDd3aXWOQtaMW'
```

The logfile doesn't seem to contain anything useful. 

This runs in a LXC container, using Docker is not trivial. I did give the Docker image a try on another box but I get a permission denied/404 on: https://hub.docker.com/r/hasmade/certbot-transip

**Comment by hsmade** [comment]
Hey, looks like transip has some strict rules about txt records. I'll go
check it out. My time is a bit sparse right now, but I'll let you know.

Groeten,

Wim

Ps: not sure if it's a typo on the Readme, but the docker repo is hsmade,
not hasmade

**Comment by BartVB** [comment]
Ah, was indeed a typo with the Docker image, oops. Still doesn't work with Docker but that's probably because I'm running it on macOS.

I changed:
https://github.com/hsmade/certbot-dns-transip/blob/master/certbot_dns_transip/dns_transip.py#L124
from `expire=1` to `expire=60`
and that solves the problem. Whoo!

Thanks a lot for this script!

It seems like a value of 60 seconds is used implicitly somewhere in the TransIP API? Matching this default value in the dns_transip.py script fixes the symptoms but it's a kludge. Script will break again when the 60 second default changes.

**Comment by hsmade** [comment]
Would be better to see if there is already a TXT record and take the TTL
from that.

**Comment by BartVB** [comment]
The TXT records are only looked up once (by Let's Encrypt) and then deleted. As far as I can tell the TTL for those records is irrelevant. They are never cached.

**Comment by hsmade** [comment]
Correct. But apparently, transip wants them to have the same TTL as the
existing ones, if they're there.
So when I have some time, or if you want do to a PR, the code should check
to see if there is an existing TXT record, and take the TTL from that, else
use the default

**Comment by BartVB** [comment]
Apparently this is not a TransIP but a DNS restriction. According to the spec records with the same name and type must have the same TTL.

In this case it's probably easiest to just delete the existing record(s) before setting them. They will be deleted anyway, so checking for an existing TTL only makes sense on the first run if the user had some left over `_acme-challenge` records. The code to delete the records is already there.

**Comment by broodjeaap** [comment]
I fixed the error by manually deleting the txt records I still had leftover after a previous manual authentication, hope it helps someone else stumbling onto this issue 👍
