### ISSUE TITLE
Small formatting issue

### ISSUE THREAD

**Issue by siccovansas** [hsmade/certbot-dns-transip#7]
On https://certbot-dns-transip.readthedocs.io/en/latest/readme.html the `--certbot-dns-transip:dns-transip-credentials transip.ini --certbot-dns-transip:dns-transip-propagation-seconds 240` part is formatted incorrectly. `--certbot-dns-transip:dns-transip-credentials` is formatted as `–certbot-dns-transip:dns-transip-credentials` (one big `–` instead of `--`), the same goes for `–certbot-dns-transip:dns-transip-propagation-seconds`.

**Comment by siccovansas** [comment]
Aah too bad. Another thing the command `certbot` is missing in front of `certonly`.

**Comment by hsmade** [comment]
No, that's part of the docker entrypoint already.
